variable vpc_id {}
variable subnet_id {}
variable my_ip {}
variable env_prefix {}
variable avail_zone {}
variable image_name {}
variable ssh-key-pair-name {}
variable public_key_location {}
variable instance_type {}
